language: php

notifications:
  email: false

php:
  - 7.2

sudo: false

cache:
  directories:
    - vendor

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit