name: Laravel Package CI

on: [push]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nanasess/setup-php@master
          with:
            php-version: '7.4'
      - name: PHP CS Fixer
        uses: StephaneBour/actions-php-cs-fixer@1.0
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nanasess/setup-php@master
          with:
            php-version: '7.4'
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit